@startuml
actor QuảnLý
participant "Màn hình quản lý va xem sự kiện " as A
participant "Màn hình xem thêm sự kiện" as B
participant "Man hình chỉnh sửa sự kiện" as C
participant "Màn hình xác nhận xóa sự kiện" as D
participant "Màn hình xác nhận thay đổi trạng thái sự kiện" as F 
participant "Màn hình xác nhận gửi email sự kiện" as G 
participant "cơ sở dữ liệu" as E


QuảnLý -> A : 1.Chọn tab Events
activate A 
A ->E : 2.Truy vấn CSDL
activate E
E --> A : 3 .Hiển thị danh sách sự kiện
deactivate E 


A -> B : 4. Chọn thêm sự kiện
activate B 
B ->B : Validate()
B -> E : 5 Truy vấn CSDL
activate E 
E --> B : 6. Lỗi không thể tạo sự kiện
deactivate B 
E --> A : 7. Thêm thành công sự kiện
deactivate E 


A -> C : 8. Chỉnh sửa sự kiện 
activate C 
C ->C :Validate()

C ->E :9 Truy vấn CSDL
activate E 
E --> C :10.  Lỗi không thể tạo sự kiện
deactivate C 
E --> A : 11. Chỉnh sửa thành công sự kiện
deactivate E 

A -> D :12. Xóa sự kiện 
activate D 
D ->E : 13.Truy vấn CSDL
activate E 
E --> D : 14.Lỗi không xóa thành công 
deactivate D 
E --> A : 15. Xóa sự kiện thành công
deactivate E 

A -> F :16. Thay đổi trạng thái sự kiện 
activate F
F ->E : 17.Truy vấn CSDL
activate E 
E --> F : 18.Lỗi không thay đổi trạng thái sự kiện thành công 
deactivate D 
E --> A : 19. Thay đổi trạng thái sự kiện thành công
deactivate E 

A -> G :20.Gửi email sự kiện 
activate G
F ->E : 21.Truy vấn CSDL
activate E 
E --> G : 22.Lỗi không gửi sự kiện thành công 
deactivate D 
E --> A : 23. .Gửi email sự kiện thành công
deactivate E 







@enduml